<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Mockery\CountValidator\Exception" namespace="Mockery\CountValidator" name="Exception" abstract="false" final="false" start="23" end="25">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/mockery/mockery/library/Mockery/CountValidator" file="Exception.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/mockery/mockery/library/Mockery/CountValidator/Exception.php" size="773" time="2015-12-17T18:44:09+00:00" unixtime="1450377849" sha1="99f4a37e71251607bfeaac9435279aa81301b6ea" relative="vendor/mockery/mockery/library/Mockery/CountValidator/Exception.php"/>
  <extends full="OutOfBoundsException" namespace="" name="OutOfBoundsException"/>
</class>
