<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="NamedMockTest" namespace="" name="NamedMockTest" abstract="false" final="false" start="24" end="54">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/mockery/mockery/tests/Mockery" file="NamedMockTest.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/mockery/mockery/tests/Mockery/NamedMockTest.php" size="1711" time="2015-12-17T18:44:09+00:00" unixtime="1450377849" sha1="be0ad45825a33e0fb4e6dcf0088c2159b0dd9f94" relative="vendor/mockery/mockery/tests/Mockery/NamedMockTest.php"/>
  <extends full="Mockery\Adapter\Phpunit\MockeryTestCase" namespace="Mockery\Adapter\Phpunit" name="MockeryTestCase"/>
  <method name="itCreatesANamedMock" start="27" end="31" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="@test"/>
    </docblock>
  </method>
  <method name="itCreatesPassesFurtherArgumentsJustLikeMock" start="34" end="42" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="@test"/>
    </docblock>
  </method>
  <method name="itShouldThrowIfAttemptingToRedefineNamedMock" start="49" end="53" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <test/>
      <expectedexception value="Mockery\Exception"/>
      <expectedexceptionmessage value="The mock named 'Mockery\Dave7' has been already defined with a different mock configuration"/>
    </docblock>
  </method>
</class>
