<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="NewException" namespace="" name="NewException" abstract="false" final="false" start="2" end="4">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpunit/phpunit/tests/Regression/GitHub/74" file="NewException.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/phpunit/phpunit/tests/Regression/GitHub/74/NewException.php" size="47" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="b3e861ae208fded807eb6ce8d1597168ed5efe6d" relative="vendor/phpunit/phpunit/tests/Regression/GitHub/74/NewException.php"/>
  <extends full="Exception" namespace="" name="Exception"/>
</class>
