<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="SuperClosure\Exception\ClosureAnalysisException" namespace="SuperClosure\Exception" name="ClosureAnalysisException" abstract="false" final="false" start="6" end="9">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/jeremeamia/SuperClosure/src/Exception" file="ClosureAnalysisException.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/jeremeamia/SuperClosure/src/Exception/ClosureAnalysisException.php" size="223" time="2015-12-17T18:44:09+00:00" unixtime="1450377849" sha1="25cde5846ab740d36f23d5a48d394a4a9919cea0" relative="vendor/jeremeamia/SuperClosure/src/Exception/ClosureAnalysisException.php"/>
  <docblock>
    <description compact="This exception is thrown when there is a problem analyzing a closure."/>
  </docblock>
  <extends full="RuntimeException" namespace="" name="RuntimeException"/>
  <implements full="SuperClosure\Exception\SuperClosureException" namespace="SuperClosure\Exception" name="SuperClosureException"/>
</class>
