<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Debug\Tests\Exception\FlattenExceptionTest" namespace="Symfony\Component\Debug\Tests\Exception" name="FlattenExceptionTest" abstract="false" final="false" start="30" end="256">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/debug/Tests/Exception" file="FlattenExceptionTest.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/debug/Tests/Exception/FlattenExceptionTest.php" size="10133" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="214a9b86a9791a74b78c95c823cb09773c0f84e8" relative="vendor/symfony/debug/Tests/Exception/FlattenExceptionTest.php"/>
  <extends full="PHPUnit_Framework_TestCase" namespace="" name="PHPUnit_Framework_TestCase"/>
  <method name="testStatusCode" start="32" end="81" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testHeadersForHttpException" start="83" end="102" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testFlattenHttpException" start="107" end="117" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <dataprovider value="flattenDataProvider"/>
    </docblock>
    <parameter name="exception" byreference="false" type="object">
      <type full="Exception" namespace="" name="Exception"/>
    </parameter>
    <parameter name="statusCode" byreference="false" type="{unknown}"/>
  </method>
  <method name="testPrevious" start="122" end="132" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <dataprovider value="flattenDataProvider"/>
    </docblock>
    <parameter name="exception" byreference="false" type="object">
      <type full="Exception" namespace="" name="Exception"/>
    </parameter>
    <parameter name="statusCode" byreference="false" type="{unknown}"/>
  </method>
  <method name="testLine" start="137" end="141" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <dataprovider value="flattenDataProvider"/>
    </docblock>
    <parameter name="exception" byreference="false" type="object">
      <type full="Exception" namespace="" name="Exception"/>
    </parameter>
  </method>
  <method name="testFile" start="146" end="150" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <dataprovider value="flattenDataProvider"/>
    </docblock>
    <parameter name="exception" byreference="false" type="object">
      <type full="Exception" namespace="" name="Exception"/>
    </parameter>
  </method>
  <method name="testToArray" start="155" end="170" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <dataprovider value="flattenDataProvider"/>
    </docblock>
    <parameter name="exception" byreference="false" type="object">
      <type full="Exception" namespace="" name="Exception"/>
    </parameter>
    <parameter name="statusCode" byreference="false" type="{unknown}"/>
  </method>
  <method name="flattenDataProvider" start="172" end="177" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testRecursionInArguments" start="179" end="187" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testTooBigArray" start="189" end="209" abstract="false" final="false" static="false" visibility="public"/>
  <method name="createException" start="211" end="214" abstract="false" final="false" static="false" visibility="private">
    <parameter name="foo" byreference="false" type="{unknown}"/>
  </method>
  <method name="testSetTraceIncompleteClass" start="216" end="255" abstract="false" final="false" static="false" visibility="public"/>
</class>
