<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Translation\Tests\IntervalTest" namespace="Symfony\Component\Translation\Tests" name="IntervalTest" abstract="false" final="false" start="16" end="48">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/translation/Tests" file="IntervalTest.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/translation/Tests/IntervalTest.php" size="1187" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="1570bec9d29dc7cc536dfc3b78030f34a768e3d1" relative="vendor/symfony/translation/Tests/IntervalTest.php"/>
  <extends full="PHPUnit_Framework_TestCase" namespace="" name="PHPUnit_Framework_TestCase"/>
  <method name="testTest" start="21" end="24" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <dataprovider value="getTests"/>
    </docblock>
    <parameter name="expected" byreference="false" type="{unknown}"/>
    <parameter name="number" byreference="false" type="{unknown}"/>
    <parameter name="interval" byreference="false" type="{unknown}"/>
  </method>
  <method name="testTestException" start="29" end="32" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <expectedexception value="\InvalidArgumentException"/>
    </docblock>
  </method>
  <method name="getTests" start="34" end="47" abstract="false" final="false" static="false" visibility="public"/>
</class>
