<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\HttpKernel\Tests\CacheWarmer\CacheWarmerTest" namespace="Symfony\Component\HttpKernel\Tests\CacheWarmer" name="CacheWarmerTest" abstract="false" final="false" start="16" end="47">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/http-kernel/Tests/CacheWarmer" file="CacheWarmerTest.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/http-kernel/Tests/CacheWarmer/CacheWarmerTest.php" size="1573" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="1e1cc9e84ee1d2853ff91376c92f5b14941bb708" relative="vendor/symfony/http-kernel/Tests/CacheWarmer/CacheWarmerTest.php"/>
  <extends full="PHPUnit_Framework_TestCase" namespace="" name="PHPUnit_Framework_TestCase"/>
  <member name="cacheFile" visibility="protected" line="18"/>
  <method name="setUpBeforeClass" start="20" end="23" abstract="false" final="false" static="true" visibility="public"/>
  <method name="tearDownAfterClass" start="25" end="28" abstract="false" final="false" static="true" visibility="public"/>
  <method name="testWriteCacheFileCreatesTheFile" start="30" end="36" abstract="false" final="false" static="false" visibility="public"/>
  <method name="testWriteNonWritableCacheFileThrowsARuntimeException" start="41" end="46" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description/>
      <expectedexception value="\RuntimeException"/>
    </docblock>
  </method>
</class>
