<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\HttpFoundation\File\Exception\FileException" namespace="Symfony\Component\HttpFoundation\File\Exception" name="FileException" abstract="false" final="false" start="19" end="21">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/http-foundation/File/Exception" file="FileException.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/http-foundation/File/Exception/FileException.php" size="466" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="fffe45a6b1c1d6c1a27de3fe7ccbe0d7f1c3d66d" relative="vendor/symfony/http-foundation/File/Exception/FileException.php"/>
  <docblock>
    <description compact="Thrown when an error occurred in the component File."/>
    <author value="Bernhard Schussek &lt;bschussek@gmail.com&gt;"/>
  </docblock>
  <extends full="RuntimeException" namespace="" name="RuntimeException"/>
</class>
