<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException" namespace="Symfony\Component\HttpKernel\Exception" name="TooManyRequestsHttpException" abstract="false" final="false" start="21" end="40">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/http-kernel/Exception" file="TooManyRequestsHttpException.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/http-kernel/Exception/TooManyRequestsHttpException.php" size="1148" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="675847c848674ab1cfb7ce6fab157a79e45d0d6b" relative="vendor/symfony/http-kernel/Exception/TooManyRequestsHttpException.php"/>
  <docblock>
    <description compact="TooManyRequestsHttpException."/>
    <author value="Ben Ramsey &lt;ben@benramsey.com&gt;"/>
    <see value="http://tools.ietf.org/html/rfc6585"/>
  </docblock>
  <extends full="Symfony\Component\HttpKernel\Exception\HttpException" namespace="Symfony\Component\HttpKernel\Exception" name="HttpException"/>
  <constructor name="__construct" start="31" end="39" abstract="false" final="false" static="false" visibility="public">
    <docblock>
      <description compact="Constructor."/>
      <param description="The number of seconds or HTTP-date after which the request may be retried" type="object" variable="$retryAfter">
        <type full="Symfony\Component\HttpKernel\Exception\int|string" namespace="Symfony\Component\HttpKernel\Exception" name="int|string"/>
      </param>
      <param description="The internal exception message" type="string" variable="$message"/>
      <param description="The previous exception" type="object" variable="$previous">
        <type full="\Exception" namespace="" name="Exception"/>
      </param>
      <param description="The internal exception code" type="int" variable="$code"/>
    </docblock>
    <parameter name="retryAfter" byreference="false" type="{unknown}" default="" constant="null"/>
    <parameter name="message" byreference="false" type="{unknown}" default="" constant="null"/>
    <parameter name="previous" byreference="false" type="{unknown}" default="" constant="null">
      <type full="Exception" namespace="" name="Exception"/>
    </parameter>
    <parameter name="code" byreference="false" type="integer" default="0"/>
  </constructor>
</class>
