<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Debug\Exception\FatalThrowableError" namespace="Symfony\Component\Debug\Exception" name="FatalThrowableError" abstract="false" final="false" start="19" end="44">
  <file path="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/debug/Exception" file="FatalThrowableError.php" realpath="/home/robert/Desktop/Hogeschool/2ejaars Development/DevBOpdrachten/project56/http/laravel/vendor/symfony/debug/Exception/FatalThrowableError.php" size="1092" time="2015-12-17T18:44:10+00:00" unixtime="1450377850" sha1="6f0a6d81a24372bd364a5b6bfca796e9ede0e30e" relative="vendor/symfony/debug/Exception/FatalThrowableError.php"/>
  <docblock>
    <description compact="Fatal Throwable Error."/>
    <author value="Nicolas Grekas &lt;p@tchwork.com&gt;"/>
  </docblock>
  <extends full="Symfony\Component\Debug\Exception\FatalErrorException" namespace="Symfony\Component\Debug\Exception" name="FatalErrorException"/>
  <constructor name="__construct" start="21" end="43" abstract="false" final="false" static="false" visibility="public">
    <parameter name="e" byreference="false" type="object">
      <type full="Throwable" namespace="" name="Throwable"/>
    </parameter>
  </constructor>
</class>
